### ISSUE TITLE
Deleting complete content removes parent div

### ISSUE THREAD

**Issue by hgrecco** [alohaeditor/Aloha-Editor#1265]
Open the aloha demo and delete all the content of the editor either by selecting all and pressing backspace or going to the end of the content and pressing backspace. You will see that the editor div is removed from the dom resulting in a total mess.

**Comment by skurfuerst** [comment]
Just stumbled across this as well, would be awesome to have that fixed :) Anything I can do to help?

**Comment by catz85** [comment]
Same problem :(

**Comment by krose72205** [comment]
Any update on this?

**Comment by AnthonyReid99** [comment]
How are you guys getting around this? As far as I can see, this bug pretty much makes aloha useless.

**Comment by yongfook** [comment]
+1

**Comment by christophermina** [comment]
+1

**Comment by DavydeVries** [comment]
+1

**Comment by Chaaph** [comment]
+1

I´ve found a (really ugly!) workaround, but i´d prefer not to use it.
http://codeviewer.org/view/code:4c53

**Comment by petrosalema** [comment]
@Chaaph my commit #0478451 should now fix this problem.
There was one place where we forgot to treat empty editing hosts as visible elements.
Thank you, everyone, for your patience.
