### ISSUE TITLE
New Aloha Editor iOS issue

### ISSUE THREAD

**Issue by florianbeer** [alohaeditor/Aloha-Editor#1269]
I've just tested the demo on the new Aloha Editor homepage. When you press the "Try it" button the cursor starts blinking in the editable section but iOS doesn't pop up the keyboard to edit content and you can't re-position the cursor by tapping.

Environment:
iOS 8.0.2 on iPad and iPhone 5 using Mobile Safari

**Comment by sferoze** [comment]
Hi Any update on this? I just installed the aloha editor and it works great on the web but in the iOS simulator it does not work at all
