### ISSUE TITLE
Best practice for minified javascript

### ISSUE THREAD

**Issue by deliminator** [alohaeditor/Aloha-Editor#1296]
The minified javascript should include an umd definition: https://github.com/umdjs/umd/blob/master/amdWeb.js

**Comment by shannmcnicholl** [comment]
This would be good. I had to debug an issue just now by tracing through the minified code and trying to match up the class and method names in github.

**Comment by petrosalema** [comment]
As of this commit (https://github.com/alohaeditor/Aloha-Editor/commit/aad0e62130e616dac2cea3658674922c14ad07a3) you can build the unminified version of the built script http://alohaeditor.org/download/aloha.js .
