### ISSUE TITLE
Syntax error in build.sh in howling-mad branch

### ISSUE THREAD

**Issue by kof** [alohaeditor/Aloha-Editor#1342]
On mac.

./build/build.sh: line 51: syntax error near unexpected token `('
./build/build.sh: line 51: `	sed s/%buildcommit%/$ish/ <(cat $entry.js) > $versioned.js'

**Comment by petrosalema** [comment]
Do you get this error if you run ```zsh build/build.sh```?

**Comment by kof** [comment]
no default shell

**Comment by petrosalema** [comment]
Fixed: https://github.com/alohaeditor/Aloha-Editor/commit/5678ca3957a6e38f350ffc8f44a12f769b6cb6c9
