### ISSUE TITLE
Binding aloha smart content changed

### ISSUE THREAD

**Issue by gpapin** [alohaeditor/Aloha-Editor#1365]
Hello,
I desperately try to bind a change event to trigger a custom function to save the changes in the database
I tried this but it's not working  :

```
var editables = aloha.dom.query('.editable', document).map(aloha);
editables.forEach(function (editable) {
	for (var command in aloha.ui.commands) {
		$('.action-' + command).on('click',
			aloha.ui.command(editable, aloha.ui.commands[command])
		);
	}
	// Test 1:
	// This doesn't work ...
	aloha.bind('aloha-smart-content-changed', function (event, eventArgument) {
		console.log('content changed !');
	});
});

// Test 2 :
// This doesn't work either ...
aloha.bind('aloha-smart-content-changed', function (event, eventArgument) {
	console.log('content changed !');
});
```
this link http://www.alohaeditor.org/guides/events.html seems outdated, any idea how to proceed ?

**Comment by petrosalema** [comment]
Please refer to the new docs at http://www.alohaeditor.org/docs/
We will add a banner to pages that are obsolete for version 2.

**Comment by gpapin** [comment]
I which I could but the new doc page is just a "Getting started" and it cover only command binding to a button. This part works that's wasn't the issue ...
