### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by paulleosteinberg** [alohaeditor/Aloha-Editor#1367]
Your license FAQ on http://www.alohaeditor.org/Content.Node/Aloha_Editor_GPL_License_FAQ.html is not entirely clear. FSF's interpretation of GPL w. r. t. JavaScript is that any code using API of GPL software has to be GPL, too.

E. g., calling "aloha.dom.query('.editable', document).forEach(aloha);" or "aloha.ui.command(aloha.ui.commands.bold));" would make all of your code (possibly all JavaScript on the same page) GPL, even entirely unrelated parts. This makes it hard to use your code in many contexts.

Is this intentional and your interpretation of the license, too?

**Comment by cprerovsky** [comment]
Hey,

sorry, changing the Aloha Editor license is nothing we're going to do anytime soon.

Cheers,
Clemens
