### ISSUE TITLE
What is the versioning scheme?

### ISSUE THREAD

**Issue by dandv** [alohaeditor/Aloha-Editor#1407]
In the [releases](https://github.com/alohaeditor/Aloha-Editor/releases), I see 1.2.18. On the website, I see 2.0.0 Alpha Build 188.

**Comment by Jotschi** [comment]
We apply [semantic versioning](http://semver.org/).
Version 2.0.0 Alpha was an early build of Aloha Editor 2 which is no longer in development.
The latest version is currently 1.4.x - http://www.alohaeditor.org/changelog/
