### ISSUE TITLE
Question about auto select after aloha(elem)

### ISSUE THREAD

**Issue by RonanDrouglazet** [alohaeditor/Aloha-Editor#1487]
Hello ! 

My issue is simple, i want to auto select my editable after calling aloha(elm) on it
i've tried : 

    aloha(element);
    aloha.selections.select(aloha.editor.selection, aloha.editor.selection.boundaries[0], aloha.editor.selection.boundaries[1], 'start');

it almost work :) the caret appears on the editable element, blinking, but we can't start modification until we click on it...it seems I've forget one things 

i need it because in some case (editable in editable), I switch editable with javascript, no user click

thanks a lot for your help !

**Comment by petrosalema** [comment]
Are you executing these commands from the developer console? If so, this would explain why you would need to put the refocus on the page before you can type.

If you want to execute the code from the developer console, and be able to type right away, then you would need to call your code using a timeout. Before the timeout fires, you would need to click into the page to give it focus.

**Comment by RonanDrouglazet** [comment]
Hi and thanks for your time !

I'm not executing this command from dev console but directly in my code.
I have some editable element inside other editable element, so in my top editable bar, I allow user to see if this editable element have other editable element inside it, and if yes, the user can select it, that's why I want to auto select the second editable element.

BUT, your response give me some clues ! Because the selection is done throught a dropdown, in other iframe, so maybe I juste loose the focus that's all ! Did i have to focus a specific element (editable) or juste the frame where the editable element are ?

**Comment by petrosalema** [comment]
Call focus() on the editable.

**Comment by RonanDrouglazet** [comment]
it works ! Thanks a lot for your help
