### ISSUE TITLE
Is there a way to add "page" breaks?

### ISSUE THREAD

**Issue by UTGuy** [alohaeditor/Aloha-Editor#1512]
ex. kinda like google docs

![image](https://cloud.githubusercontent.com/assets/1872858/13272699/00bb9b2a-da6c-11e5-92c4-39221d3a5916.png)

**Comment by bernhardriegler** [comment]
Aloha Editor uses contenteditable (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable) to generate valid HTML.

Page breaks are only used when when printing.

What you can do however is inserting an HTML element accompanied by some styling to achieve this:

https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after

This can be done by writing a plugin that adds a button to the Aloha Editor floating menu. On click of that button a "page-break-element" can be inserted after the current paragraph.

For example:
```
<div style="page-break-after: always;"></div>
```
Note that using a class and moving the style rule to a stylesheet file is preferable.

Please refer to the [Aloha Editor guides on how to write plugins](https://www.alohaeditor.org/guides/writing_plugins.html) for more info on creating your plugin.
