### ISSUE TITLE
Image plugin does not disable

### ISSUE THREAD

**Issue by ghost** [alohaeditor/Aloha-Editor#714]
analyzing the source code of this example http://aloha-editor.org/demos/3col/ noticed that the image plugin is disabled, but the option to add image still appears in the floating menu. I have a similar code where I need to disable the plugin for image titles, however, it does not disable.

**Comment by nir98tak** [comment]
> analyzing the source code of this example http://aloha-editor.org/demos/3col/ noticed that the image plugin is disabled, but the option to add image still appears in the floating menu. I have a similar code where I need to disable the plugin for image titles, however, it does not disable.
