### ISSUE TITLE
Problems editing content in an iframe

### ISSUE THREAD

**Issue by karger** [alohaeditor/Aloha-Editor#734]
I'm  writing an application that uses Aloha (loaded in the parent window) to edit content in an iframe.  Yes, you could ask why I need an iframe when aloha is all about in-place editing, but there are good reasons.  My efforts are revealing that Aloha has baked in, I think unnecessarily, an assumption that the editable content and the aloha scripts are in the same window.  For example, when I call $().mahalo() it invokes Aloha.getEditableById(jQuery(this).attr('id')).destroy();  Then, getEditableById(id) invokes jQuery('#'+id).get(0) .  Since the node with the given id was inside the iframe, jQuery('#'+id) has no match (in the parent window), so get(0) returns null which crashes mahalo.  This was unnecessary, as the nodes you used getEditableById to find were already in hand during the mahalo() invocation.

This is not only a problem with an iframe but also if I edit content in a second window.  

A solution here would be a method getEditable(node) which, instead of being passed an id, is passed a jquery node whose editable you want to find.  Since you already have the node in hand, you don't need to use jquery to find the node. 

Any "absolute" jquery selector, which is implicitly scoped to the current document, offers the same potential problem.  Selectors scoped relative to some preexisting jquery do not.

**Comment by eob** [comment]
Well I just searched for the same problem and lo and behold I find you as the top search result David -- Small world :)
