### ISSUE TITLE
Copy&Paste of images does not work

### ISSUE THREAD

**Issue by evo42** [alohaeditor/Aloha-Editor#797]
When the image plugin is activated it's not possible to copy&paste an image.

**Comment by dandv** [comment]
Two years later, pasting images is a highly requested feature. GitHub, StackOverflow, Slack, Imgur - all implement it. The online demo at http://www.alohaeditor.org/demo/aloha-ui/ doesn't support pasting images.

Many other editors get this right: Summernote, Froala etc.
